name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cd simple-working
          git submodule update --init --recursive
          docker-compose up -d
